# This workflow will build a Java project with Ant
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: 'Checkout submodules'
      uses: textbook/git-checkout-submodule-action@master
    - name: 'Install 32-bit dependencies'
      run: sudo apt-get install -y libc6-i386 lib32z1 lib32stdc++6
    - name: 'Make Auth Key'
      run: ant MakeAuthKey
      working-directory: appinventor
    - name: 'Build Appinventor'
      run: ant noplay
      working-directory: appinventor
    - name: 'Run Tests'
      run: ant tests
      working-directory: appinventor
    - name: 'Upload Test Reports to Artifacts'
      uses: actions/upload-artifact@v1.0.0
      with:
          name: Test Reports
          path: appinventor/reports
    - name: 'Build Companion'
      run: ant PlayApp
      working-directory: appinventor
    - name: 'Upload Companion to Artifacts'
      uses: actions/upload-artifact@v1.0.0
      with:
          name: MIT AI2 Companion
          path: appinventor/build/buildserver/MIT AI2 Companion.apk
    
